name: 💡 Feature Request
description: Suggest a new feature or enhancement for PersonaFlow
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to suggest a new feature! Please fill out the following information to help us understand your request.

  - type: textarea
    id: feature-description
    attributes:
      label: 💡 Feature Description
      description: A clear and concise description of the feature you'd like to see.
      placeholder: Describe the feature...
    validations:
      required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: 🏷️ Feature Type
      description: What type of feature is this?
      options:
        - AI/ML Enhancement
        - User Interface Improvement
        - API Enhancement
        - Integration
        - Performance Optimization
        - Developer Experience
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: 🎯 Problem Statement
      description: What problem does this feature solve? What's the current limitation?
      placeholder: |
        Is your feature request related to a problem? Please describe.
        e.g., "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: ✨ Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: 🔄 Use Cases
      description: Describe specific use cases where this feature would be valuable.
      placeholder: |
        1. As a researcher, I want to... so that I can...
        2. When working on..., I need to... because...
    validations:
      required: true

  - type: dropdown
    id: user-type
    attributes:
      label: 👤 User Type
      description: Who would primarily benefit from this feature?
      options:
        - Researchers
        - Developers
        - System Administrators
        - End Users
        - All Users
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 🔥 Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Significantly impacts productivity
        - Critical - Blocking current work
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: What other approaches could solve this problem?

  - type: textarea
    id: implementation-ideas
    attributes:
      label: 🛠️ Implementation Ideas
      description: If you have ideas about how this could be implemented, please share them.
      placeholder: |
        Any thoughts on:
        - UI/UX design
        - Technical approach
        - API design
        - Integration points

  - type: textarea
    id: mockups
    attributes:
      label: 🎨 Mockups/Examples
      description: If applicable, add mockups, wireframes, or examples from other tools.
      placeholder: You can paste images directly here or drag and drop them.

  - type: textarea
    id: additional-context
    attributes:
      label: 📝 Additional Context
      description: Add any other context, screenshots, or examples about the feature request.
      placeholder: Any additional information that might be helpful...

  - type: checkboxes
    id: terms
    attributes:
      label: ✅ Confirmation
      description: By submitting this issue, you confirm that...
      options:
        - label: I have searched for existing issues to avoid duplicates
          required: true
        - label: I have provided a clear description of the feature and its benefits
          required: true
        - label: I understand this may not be implemented immediately
          required: true 