# Frontend Dockerfile
FROM node:20 as frontend_build

RUN apt-get update && apt-get install -y \
    jq 
RUN npm install -g pnpm@8.6.7

WORKDIR /app

ARG BACKEND_URL
ENV BACKEND_URL $BACKEND_URL
RUN echo "BACKEND_URL: $BACKEND_URL"


COPY package*.json ./

RUN pnpm install

COPY . .

COPY ./set_proxy.sh .
RUN chmod +x set_proxy.sh && \
    cat set_proxy.sh | tr -d '\r' > set_proxy_unix.sh && \
    chmod +x set_proxy_unix.sh && \
    ./set_proxy_unix.sh

RUN pnpm run build

FROM nginx
COPY --from=frontend_build /app/build/ /usr/share/nginx/html
COPY /nginx.conf /etc/nginx/conf.d/default.conf
COPY start-nginx.sh /start-nginx.sh
RUN chmod +x /start-nginx.sh

COPY ./env.sh /env.sh
RUN chmod +x /env.sh

# ENV BACKEND_URL=$BACKEND_URL
CMD ["/bin/sh", "-c", "/env.sh && /start-nginx.sh"]
# CMD ["pnpm", "run", "dev", "--host"]