import { Cog6ToothIcon, TrashIcon } from "@heroicons/react/24/outline"
import {
  classNames,
  nodeColors,
  nodeIcons,
  snakeToNormalCase,
} from "../../utils"
import ParameterComponent from "./components/parameterComponent"
import { typesContext } from "../../contexts/typesContext"
import { useContext, useState, useEffect, useRef } from "react"
import { NodeDataType } from "../../types/flow"
import { alertContext } from "../../contexts/alertContext"
import { PopUpContext } from "../../contexts/popUpContext"
import NodeModal from "../../modals/NodeModal"
import { useCallback } from "react"
import { TabsContext } from "../../contexts/tabsContext"

import { contextMenuContext } from "../../contexts/contextMenuContext"
import { background } from "@chakra-ui/system"

import RobotIcon from "../../../public/RobotIcon.svg"

import { Textarea, Button, IconButton } from "@material-tailwind/react"
import { LinkIcon } from "@heroicons/react/24/outline"

import Accordion from "@mui/material/Accordion"
import AccordionSummary from "@mui/material/AccordionSummary"
import AccordionDetails from "@mui/material/AccordionDetails"
import ExpandMoreIcon from "@mui/icons-material/ExpandMore"
import { CircularProgress } from "@mui/material"

import Likert from "react-likert-scale"
import AccordionLikert from "../components/AccordionLikert"

import InteractiveTutorialComponent from "../../pages/FlowPage/components/InteractiveTutorialComponent"
import { InteractiveTutorialContext } from "../../contexts/InteractiveTutorialContext"
import FavButton from "../components/FavButton"

export default function RQNode({
  data,
  selected,
}: {
  data: NodeDataType
  selected: boolean
}) {
  const { setErrorData } = useContext(alertContext)
  const showError = useRef(true)
  const { types, deleteNode } = useContext(typesContext)
  const { openPopUp } = useContext(PopUpContext)
  const Icon = nodeIcons[types[data.type]]
  const [validationStatus, setValidationStatus] = useState("idle")
  // State for outline color
  const [isValid, setIsValid] = useState(false)
  const { save } = useContext(TabsContext)
  const { reactFlowInstance } = useContext(typesContext)
  const [params, setParams] = useState([])
  const [_, forceUpdate] = useState(0)

  const {
    isInteractiveTutorialOpen,

    currentStep,
  } = useContext(InteractiveTutorialContext)
  // add mapping of nodeid --> loading props to context
  const {
    loadingStates,
    setLoadingForNode,
    setCurrentNode,
    currentNode,
    setRatedNodesById,
  } = useContext(contextMenuContext)

  const likertConfigs = {
    items: [
      {
        question: "This RQ is relevant to the research topic.",
        tag: "relevance",
      },
      {
        question:
          "This RQ provides me with new insights that I had not considered before.",
        tag: "creativity",
      },
      {
        question: "This RQ is feasible for conducting further research.",
        tag: "feasibility",
      },
      {
        question: "This RQ is specific and clear.",
        tag: "specificity",
      },
    ],
    responses: [
      { value: 1, text: "Strongly Disagree" },
      { value: 2, text: "Disagree" },
      { value: 3, text: "Neutral" },
      { value: 4, text: "Agree" },
      { value: 5, text: "Strongly Agree" },
    ],
  }

  console.log()

  useEffect(() => {
    if (reactFlowInstance?.toObject) {
      setParams(Object.values(reactFlowInstance.toObject()))
    }
  }, [save])

  useEffect(() => {
    // 	try {
    // 		fetch(`/validate/node/${data.id}`, {
    // 			method: "POST",
    // 			headers: {
    // 				"Content-Type": "application/json",
    // 			},
    // 			body: JSON.stringify(reactFlowInstance.toObject()),
    // 		}).then((response) => {
    // 			console.log(response.status, response.body);

    // 			if (response.status === 200) {
    // 				setValidationStatus("success");
    // 			} else if (response.status === 500) {
    // 				setValidationStatus("error");
    // 			}
    // 		});
    // 	} catch (error) {
    // 		console.error("Error validating node:", error);
    // 		setValidationStatus("error");
    // 	}

    // TODO: override this behavior for now
    if (data.userInput) {
      setValidationStatus("success")
    } else {
      setValidationStatus("failed")
    }
  }, [params])

  useEffect(() => {
    if (currentNode?.data?.type === "RQNode") {
      if (isInteractiveTutorialOpen && !currentNode?.data?.autoGenerated) {
        currentNode.data.userInput =
          "Exploring the effectiveness of generative adversarial networks (GANs) in enhancing data augmentation for imbalanced datasets."
      }
    }
  }, [currentStep, currentNode, isInteractiveTutorialOpen])

  useEffect(() => {
    if (validationStatus === "success") {
      setIsValid(true)
    } else {
      setIsValid(false)
    }

    // // check if node.data.value and node.data.userInput are both null
    // // if so, set current node to self
    // if (data.value === null && data.userInput === null) {
    // 	let node = reactFlowInstance.getNode(data.id);
    // 	selected = true;
    // 	// node.click();
    // }
  }, [validationStatus])

  if (!Icon) {
    if (showError.current) {
      setErrorData({
        title: data.type
          ? `The ${data.type} node could not be rendered, please review your json file`
          : "There was a node that can't be rendered, please review your json file",
      })
      showError.current = false
    }
    deleteNode(data.id)
    return
  }

  const childComponent = (
    <div
      className={classNames(
        isValid
          ? "animate-pulse-green"
          : "animate-pulse-red border-red-outline",
        // isValid ? "animate-pulse-green" : "animate-pulse-red",
        selected ? "border border-blue-500" : "border dark:border-gray-700",
        "prompt-node relative flex w-128 flex-col justify-center rounded-lg bg-yellow-100 text-xl dark:bg-yellow-100",
      )}
    >
      {loadingStates[data.id] && (
        <>
          <div className="absolute top-0 right-0 m-6">
            <svg width={0} height={0}>
              <defs>
                <linearGradient
                  id="custom_gradient"
                  x1="0%"
                  y1="0%"
                  x2="0%"
                  y2="100%"
                >
                  {/* blue to green */}
                  <stop offset="0%" stopColor="#2563EB" />
                  <stop offset="100%" stopColor="#38A169" />
                </linearGradient>
              </defs>
            </svg>
            <CircularProgress
              size={50}
              thickness={4}
              sx={{
                "svg circle": { stroke: "url(#custom_gradient)" },
              }}
            />
          </div>
        </>
      )}

      {/* check if hide header in schema and is true */}
      {data.node.hide_header ? null : (
        <div className="flex w-full items-center justify-between gap-8 rounded-t-lg border-b bg-gray-50 p-4 dark:border-b-gray-700 dark:bg-gray-800 dark:text-white ">
          <div className="flex w-full items-center gap-4 truncate text-lg">
            <Icon
              className="h-10 w-10 rounded p-1"
              style={{
                color: nodeColors[types[data.type]] ?? nodeColors.unknown,
              }}
            />
            <div className="truncate">{data.type}</div>
          </div>
          <div className="flex gap-3">
            <button
              className="relative"
              onClick={(event) => {
                event.preventDefault()
                openPopUp(<NodeModal data={data} />)
              }}
            >
              <div className=" absolute -right-1 -top-2 text-red-600">
                {Object.keys(data.node.template).some(
                  (t) =>
                    data.node.template[t].advanced &&
                    data.node.template[t].required,
                )
                  ? " *"
                  : ""}
              </div>
              <Cog6ToothIcon
                className={classNames(
                  Object.keys(data.node.template).some(
                    (t) =>
                      data.node.template[t].advanced &&
                      data.node.template[t].show,
                  )
                    ? ""
                    : "hidden",
                  "h-6 w-6  hover:animate-spin  dark:text-gray-500",
                )}
              ></Cog6ToothIcon>
            </button>
            <button
              onClick={() => {
                deleteNode(data.id)
              }}
            >
              <TrashIcon className="h-6 w-6 hover:text-red-500 dark:text-gray-500 dark:hover:text-red-500"></TrashIcon>
            </button>
          </div>
        </div>
      )}

      <div className="shrink-0 rounded-lg border-sky-900 bg-[#FFF6DB] px-5 py-5 shadow-xl">
        <div className="flex w-full items-center gap-2 truncate text-2xl">
          <Icon
            className="h-14 w-14 rounded p-1"
            style={{
              color: nodeColors.unknown,
            }}
          />
          <div className="truncate font-bold">Research Question</div>
          <FavButton nodeData={data} />
        </div>
        {selected ? (
          // <div className="w-full h-full py-5">
          <div>
            <div className="w-full px-5 pb-3 text-sm text-gray-500">
              {data.node.description}
            </div>

            <>
              {Object.keys(data.node.template)
                .filter((t) => t.charAt(0) !== "_")
                .map((t: string, idx) => (
                  <div key={idx}>
                    {data.node.template[t].show &&
                    !data.node.template[t].advanced ? (
                      <ParameterComponent
                        data={data}
                        color={
                          nodeColors[types[data.node.template[t].type]] ??
                          nodeColors.unknown
                        }
                        title={data.value ? data.node.template[t].name : ""}
                        name={t}
                        tooltipTitle={
                          "Type: " +
                          data.node.template[t].type +
                          (data.node.template[t].list ? " list" : "")
                        }
                        required={data.node.template[t].required}
                        id={
                          data.node.template[t].type + "|" + t + "|" + data.id
                        }
                        left={true}
                        type={data.node.template[t].type}
                        selected={selected}
                      />
                    ) : (
                      <></>
                    )}
                  </div>
                ))}
              <div
                className={classNames(
                  Object.keys(data.node.template).length < 1 ? "hidden" : "",
                  "w-full flex justify-center",
                )}
              >
                {" "}
              </div>

              {data?.autoGenerated &&
                AccordionLikert({
                  likertConfigs: likertConfigs,
                  validationStatus: validationStatus,
                  nodeData: data,
                })}

              <ParameterComponent
                data={data}
                color={nodeColors[types[data.type]] ?? nodeColors.unknown}
                title={data.type}
                tooltipTitle={`Type: ${data.node.base_classes.join(" | ")}`}
                id={[data.type, data.id, ...data.node.base_classes].join("|")}
                type={data.node.base_classes.join("|")}
                left={false}
                selected={selected}
              />
            </>
          </div>
        ) : (
          // Only display data.value if not selected
          // <div className="w-full h-full py-5 px-5 bg-gray-200">
          <div>
            {Object.keys(data.node.template)
              .filter((t) => t.charAt(0) !== "_")
              .slice(0, 1)
              .map((t: string, idx) => (
                <div key={idx}>
                  {data.node.template[t].show &&
                  !data.node.template[t].advanced ? (
                    <ParameterComponent
                      data={data}
                      color={
                        nodeColors[types[data.node.template[t].type]] ??
                        nodeColors.unknown
                      }
                      title={data.node.template[t].name}
                      name={t}
                      tooltipTitle={
                        "Type: " +
                        data.node.template[t].type +
                        (data.node.template[t].list ? " list" : "")
                      }
                      required={data.node.template[t].required}
                      id={data.node.template[t].type + "|" + t + "|" + data.id}
                      left={true}
                      type={data.node.template[t].type}
                      selected={selected}
                    />
                  ) : (
                    <></>
                  )}
                </div>
              ))}
            {data.userInput ? (
              <>
                {/* <div className="text-xl font-bold">RQ: </div> */}
                <div>{data.userInput}</div>
              </>
            ) : (
              ""
            )}
            <ParameterComponent
              data={data}
              color={nodeColors[types[data.type]] ?? nodeColors.unknown}
              title={""}
              tooltipTitle={`Type: ${data.node.base_classes.join(" | ")}`}
              id={[data.type, data.id, ...data.node.base_classes].join("|")}
              type={data.node.base_classes.join("|")}
              left={false}
              selected={selected}
            />
          </div>
        )}
      </div>
    </div>
  )

  return isInteractiveTutorialOpen &&
    (currentStep < 4 || currentStep === 11) ? (
    <InteractiveTutorialComponent targetTutorialStep={1} childNodeId={data.id}>
      {childComponent}
    </InteractiveTutorialComponent>
  ) : childComponent
}
