import { ChatMessageType } from "./../chat/index";
import { APIClassType } from "../api/index";
import { ReactFlowJsonObject, XYPosition } from "reactflow";

export type FlowType = {
  name: string;
  id: string;
  data: ReactFlowJsonObject;
  description: string;
};
export type NodeType = {
  id: string;
  type?: string;
  position: XYPosition;
  data: NodeDataType;
  style?: {};
};
export type NodeDataType = {
  label?: string;
  type: string;
  node?: APIClassType;
  id: string;
  value: any;
  filterIDs: string[] | null;
  lockedIDs: string[] | null;
  userInput: string | null;
  valueDict: { [key: string]: any };
  autoGenerated?: boolean;
  favorited?: boolean;
};
